## Activity 02: Indexing, Slicing, and Iterating
>## Ivan Zepeda
**C0883949**

Our client wants to prove that our dataset is nicely distributed around the mean value of 100.   
They asked us to run some tests on several subsections of it to make sure they won't get a non-descriptive section of our data.

Look at the mean value of each subtask.

#### Loading the dataset

In [1]:
# importing the necessary dependencies
import numpy as np

In [ ]:
# loading the Dataset`
dataset = np.genfromtxt('./data/normal_distribution.csv', delimiter=',')

In [12]:
dataset

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189,
        101.34745901],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942,
         93.87155456],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286,
        107.22482426],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803,
        103.40412146],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732,
         96.10020311],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416,
         97.62787811],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.4649

---

#### Indexing

Since we need several rows of our dataset to complete the given task, we have to use indexing to get the right rows.   
To recap, we need: 
- the second row 
- the last row
- the first value of the first row
- the last value of the second to the last row

In [4]:
# indexing the second row of the dataset (2nd row)
dataset[1]


array([ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
        92.9267508 ,  92.65657752, 105.7197853 , 101.23162942,
        93.87155456])

In [5]:
# indexing the last element of the dataset (last row)
dataset[-1]


array([ 94.11176915,  99.62387832, 104.51786419,  97.62787811,
        93.97853495,  98.75108352, 106.05042487, 100.07721494,
       106.89005002])

In [9]:
# indexing the first value of the second row (1st row, 1st value)
print("1 value, 2nd row: \t",dataset[1,0])
print("1st row, 1st value: \t",dataset[0,0])


1 value, 2nd row: 	 92.02628776
1st row, 1st value: 	 99.14931546


In [40]:
# indexing the last value of the second to last row (we want to use the combined access syntax here) 
print(dataset[-2][-1])
dataset[-2,-1]


101.2226037


101.2226037

> The expressions dataset[-2][-1] and dataset[-2, -1] are not the same and will yield different results.  
Let's assume dataset is a 2D NumPy array for clarity.  
dataset[-2][-1]: This expression first accesses the second-to-last row of the dataset using dataset[-2], and then retrieves the last element of that row using [-1]. In other words, it performs two separate indexing operations.  
dataset[-2, -1]: This expression performs a single indexing operation using a tuple of indices (-2, -1). It accesses the element at the second-to-last row and last column of the dataset.  
Both expressions will output 6 in this case because the second-to-last row's last element in the dataset is 6.   However, the key distinction lies in how the indexing is performed, with dataset[-2][-1] using sequential indexing operations and dataset[-2, -1] utilizing a single indexing operation with a tuple of indices.

---

#### Slicing

Other than the single rows and values we also need to get some subsets of the dataset.   
Here we want slices:
- a 2x2 slice starting from the second row and second element to the 4th element in the 4th row
- every other element of the 5th row
- the content of the last row in reversed order

In [16]:
# slicing an intersection of 4 elements (2x2) of the first two rows and first two columns
print(dataset[:5,:5])
d2=dataset[1:3,1:3]
d2


[[ 99.14931546 104.03852715 107.43534677  97.85230675  98.74986914]
 [ 92.02628776  97.10439252  99.32066924  97.24584816  92.9267508 ]
 [ 95.66253664  95.17750125  90.93318132 110.18889465  98.80084371]
 [ 91.37294597 100.96781394 100.40118279 113.42090475 105.48508838]
 [101.20862522 103.5730309  100.28690912 105.85269352  93.37126331]]


array([[97.10439252, 99.32066924],
       [95.17750125, 90.93318132]])

##### Why is it not a problem if such a small subsection has a bigger standard deviation from 100?

Several smaller values can cluster in such a small subsection leading to the value being really low.   
If we make our subsection larger, we have a higher chance of getting a more expressive view of our data.

In [24]:
# selecting every second element of the fifth row 
#- every other element of the 5th row
# print(dataset[4])
# print(dataset[4,::1]) # Steps stars form 1 base indexing. therefore, 1, will show each element
print("5th row , every other column:\n",dataset[4,::2])


5th row , every other column:
 [101.20862522 100.28690912  93.37126331 100.79478953  96.10020311]


In [25]:
# reversing the entry order, selecting the first two rows in reversed order



#- the content of the last row in reversed order
print("lastrow:\n",dataset[-1])
print("last row, reverse order:\n",dataset[-1,::-1])


lastrow:
 [ 94.11176915  99.62387832 104.51786419  97.62787811  93.97853495
  98.75108352 106.05042487 100.07721494 106.89005002]
last row, reverse order:
 [106.89005002 100.07721494 106.05042487  98.75108352  93.97853495
  97.62787811 104.51786419  99.62387832  94.11176915]


---

#### Splitting

Our client's team only wants to use a small subset of the given dataset.   
Therefore we need to first split it into 3 equal pieces and then give them the first half of the first split.   
They sent us this drawing to show us what they need:
```
1, 2, 3, 4, 5, 6          1, 2     3, 4    5, 6          1, 2  
3, 2, 1, 5, 4, 6    =>    3, 2     1, 5    4, 6    =>    3, 2    =>    1, 2
5, 3, 1, 2, 4, 3          5, 3     1, 2    4, 3                        3, 2
1, 2, 2, 4, 1, 5          1, 2     2, 4    1, 5          5, 3
                                                         1, 2
```

> **Note:**   
We are using a very small dataset here but imagine you have a huge amount of data and only want to look at a small subset of it to tweak your visualizations

In [29]:
# splitting up our dataset horizontally on indices one third and two thirds
d3=dataset.copy()
# thirds=[]
# for i in range(3):
#     a=i*len(d3//3)
#     b=i*len(d3//3)*3
#     thirds.append(d3[:,a:b])
# print(thirds[0])
# print(thirds[0][:len(thirds[0])//2])

# SECOND APPROACH
# # Calculating the splitting indices
# num_columns = data.shape[1]
# split_indices = np.round(np.array([num_columns/3, 2*num_columns/3])).astype(int) => [3,6]
# # Splitting the dataset horizontally on the calculated indices
# left, middle, right = np.hsplit(data, split_indices) => hsplit can use multiple splits

# THIRD APPROACH
print(d3.shape)
d4=d3[:d3.shape[0]//2, :d3.shape[1]//3]
print(d4.shape)
d4

(24, 9)
(12, 3)


array([[ 99.14931546, 104.03852715, 107.43534677],
       [ 92.02628776,  97.10439252,  99.32066924],
       [ 95.66253664,  95.17750125,  90.93318132],
       [ 91.37294597, 100.96781394, 100.40118279],
       [101.20862522, 103.5730309 , 100.28690912],
       [102.80387079,  98.29687616,  93.24376389],
       [106.71751618, 102.97585605,  98.45723272],
       [ 96.02548256, 102.82360856, 106.47551845],
       [105.30350449,  92.87730812, 103.19258339],
       [110.44484313,  93.87155456, 101.5363647 ],
       [101.3514185 , 100.37372248, 106.6471081 ],
       [ 97.21315663, 107.02874163, 102.17642112]])

In [35]:
# splitting up our dataset vertically on index 2
da = dataset[:2]
db = dataset[2:]
print(da.shape)
print(db.shape)

# Using built in functions
d2a,d2b = np.hsplit(dataset, [2])


(2, 9)
(22, 9)


---

#### Iterating

Once you sent over the dataset they tell you that they also need a way iterate over the whole dataset element by element as if it would be a one-dimensional list.   
However, they want to also now the position in the dataset itself.

They send you this piece of code and tell you that it's not working as mentioned.   
Come up with the right solution for their needs.

In [36]:
# iterating over whole dataset (each value in each row)
curr_index = 0
for x in np.nditer(dataset):
    print(x, curr_index)
    curr_index += 1

99.14931546 0
104.03852715 1
107.43534677 2
97.85230675 3
98.74986914 4
98.80833412 5
96.81964892 6
98.56783189 7
101.34745901 8
92.02628776 9
97.10439252 10
99.32066924 11
97.24584816 12
92.9267508 13
92.65657752 14
105.7197853 15
101.23162942 16
93.87155456 17
95.66253664 18
95.17750125 19
90.93318132 20
110.18889465 21
98.80084371 22
105.95297652 23
98.37481387 24
106.54654286 25
107.22482426 26
91.37294597 27
100.96781394 28
100.40118279 29
113.42090475 30
105.48508838 31
91.6604946 32
106.1472841 33
95.08715803 34
103.40412146 35
101.20862522 36
103.5730309 37
100.28690912 38
105.85269352 39
93.37126331 40
108.57980357 41
100.79478953 42
94.20019732 43
96.10020311 44
102.80387079 45
98.29687616 46
93.24376389 47
97.24130034 48
89.03452725 49
96.2832753 50
104.60344836 51
101.13442416 52
97.62787811 53
106.71751618 54
102.97585605 55
98.45723272 56
100.72418901 57
106.39798503 58
95.46493436 59
94.35373179 60
106.83273763 61
100.07721494 62
96.02548256 63
102.82360856 64
106.475518

In [38]:
dataset[0][:3]

array([ 99.14931546, 104.03852715, 107.43534677])

In [42]:
# iterating over the whole dataset with indices matching the position in the dataset
    
for index, value in np.ndenumerate(dataset):
    print("Index:",index," \t Value:",value)

Index: (0, 0)  	 Value: 99.14931546
Index: (0, 1)  	 Value: 104.03852715
Index: (0, 2)  	 Value: 107.43534677
Index: (0, 3)  	 Value: 97.85230675
Index: (0, 4)  	 Value: 98.74986914
Index: (0, 5)  	 Value: 98.80833412
Index: (0, 6)  	 Value: 96.81964892
Index: (0, 7)  	 Value: 98.56783189
Index: (0, 8)  	 Value: 101.34745901
Index: (1, 0)  	 Value: 92.02628776
Index: (1, 1)  	 Value: 97.10439252
Index: (1, 2)  	 Value: 99.32066924
Index: (1, 3)  	 Value: 97.24584816
Index: (1, 4)  	 Value: 92.9267508
Index: (1, 5)  	 Value: 92.65657752
Index: (1, 6)  	 Value: 105.7197853
Index: (1, 7)  	 Value: 101.23162942
Index: (1, 8)  	 Value: 93.87155456
Index: (2, 0)  	 Value: 95.66253664
Index: (2, 1)  	 Value: 95.17750125
Index: (2, 2)  	 Value: 90.93318132
Index: (2, 3)  	 Value: 110.18889465
Index: (2, 4)  	 Value: 98.80084371
Index: (2, 5)  	 Value: 105.95297652
Index: (2, 6)  	 Value: 98.37481387
Index: (2, 7)  	 Value: 106.54654286
Index: (2, 8)  	 Value: 107.22482426
Index: (3, 0)  	 Valu

**NOTE:**  
- **nditer**: will iterate each element, returning the next item at each loop
- **ndenumerate**: will enumerate each object, returning index and next.item